### ISSUE TITLE
有否考虑支持同时更新多个子域名？

### ISSUE THREAD

**Issue by czszj** [chenhw2/aliyun-ddns-cli#10]
同时运行多个Container感觉浪费了一点。能否支持同时刷新多个子域名？

**Comment by chenhw2** [comment]
意义?
如果需要多个域名指向同一个IP的话, 只更新一个域名, 然后其他域名CNAME到这个域名会更好

**Comment by czszj** [comment]
确实CNAME也是可以的，不过被ping的时候就露底了。

**Comment by czszj** [comment]
想了一下，可以只更新主域名。再把其他次级域名CNAME到主域名。这样就不会暴露了。这个需求可以忽略。
