### ISSUE TITLE
请问一下，我的外网是双IP的问题？

### ISSUE THREAD

**Issue by daoyuanjiao** [chenhw2/aliyun-ddns-cli#15]
我的是两路wan进入，有两个外网IP地址，现在用这个后，每10分钟自动更新一次，但会出现两个IP交替更新（实际上是两个外网IP，但是一直是一样的），导致网址无法访问的问题。这个怎么解决呢？谢谢！

**Comment by chenhw2** [comment]
Try add param: `--ipapi http://www.taobao.com/help/getip.php`
