### ISSUE TITLE
請問多長時間更一次IP

### ISSUE THREAD

**Issue by sillydanny** [chenhw2/aliyun-ddns-cli#17]
我的不是FIX IP, 每一段時間就會更新一次新IP. 請問用群輝DOCKER安裝, 會自動隔一段時間更新IP嗎? 謝謝chenhw2大神!!

**Comment by chenhw2** [comment]
Refer: `REDO`
![](https://raw.githubusercontent.com/chenhw2/aliyun-ddns-cli/master/example/Synology_Docker.png)
