### ISSUE TITLE
 Aliyun API Error: RequestId:  Status Code: -1 Code: 

### ISSUE THREAD

**Issue by hukecolin** [chenhw2/aliyun-ddns-cli#4]
DSM 6.1-15047        Use the updated version
2017/08/15 14:22:27 Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: json: cannot unmarshal string into Go struct field RecordType.TTL of type int32

**Comment by chenhw2** [comment]
Have U update the docker?

**Comment by hukecolin** [comment]
The Docker version is 1.11.2-0329, and is the latest version in the synology suite.

**Comment by chenhw2** [comment]
Update the Docker of ```chenhw2/aliyun-ddns-cli```

```docker pull chenhw2/aliyun-ddns-cli```

**Comment by i6941** [comment]
same issue,Status: Image is up to date for chenhw2/aliyun-ddns-cli:latest

**Comment by chenhw2** [comment]
How often this error comes up?
In My DSM, it only comes up 5 times in the last 24 hour, which i think it doesn't master.

**Comment by hukecolin** [comment]
If IP and domain resolution are correct, the domain name and IP are displayed in the log. An error occurs whenever the domain name and IP parse do not correspond to each other. And the error is to parse the error once.

**Comment by chenhw2** [comment]
I meet the same issue now. I will try to fix this.

Problem comes from https://github.com/denverdino/aliyungo/issues/148

**Comment by chenhw2** [comment]
try https://github.com/chenhw2/aliyun-ddns-cli/commit/0eaac3b1512aa482b7dfdf4860db412fd76b184b and the latest docker

**Comment by hukecolin** [comment]
Download the latest version of chenhw2/aliyun-ddns-cli1, parsing normal. Prepare for long runs to see stability. Thank you

**Comment by i6941** [comment]
It seems ok now，thank you
