### ISSUE TITLE
TTL类型还是出错，无法完成解析

### ISSUE THREAD

**Issue by Soolita** [chenhw2/aliyun-ddns-cli#5]
开了两个解析，一个www.xxxx.com是正常的，另一个@.xxxx.com会提示下面的错误：
2017/09/07 20:30:08 Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: json: cannot unmarshal number into Go struct field RecordTypeNew.TTL of type string

**Comment by chenhw2** [comment]
this will be fixed soon.

**Comment by chenhw2** [comment]
fixed in https://github.com/chenhw2/aliyun-ddns-cli/commit/c971ea6e6ecee453fc9edbf7e03559cc146aaff7
