### ISSUE TITLE
Can't work:Aliyun API Error

### ISSUE THREAD

**Issue by michaelauto** [chenhw2/aliyun-ddns-cli#6]
it works fine at beginning
and a week later says:
Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: json: cannot unmarshal number into Go struct field RecordTypeNew.TTL of type string | stdout

**Comment by chenhw2** [comment]
```Last pushed: 7 days ago```

Plz Update the lastest Docker.
