### ISSUE TITLE
群晖5.2下出错

### ISSUE THREAD

**Issue by happy8109** [chenhw2/aliyun-ddns-cli#7]
日志：
2017/10/11 12:13:07 Aliyun API Error: RequestId: 7EF4C83D-86EF-4F77-8CEF-9BECE19776AA Status Code: 400 Code: InvalidTimeStamp.Expired Message: Specified time stamp or date value is expired.

**Comment by chenhw2** [comment]
没有5.2的设备，没办法测试，看起来像是时区的问题
