### ISSUE TITLE
获取ip是不是有问题？

### ISSUE THREAD

**Issue by qianjun2659** [chenhw2/aliyun-ddns-cli#8]
我是北京鹏博士宽带，刚才使用不到半个小时出来一大堆ip（和群晖自带的ddnsip都不同）。好像这类小区宽带的ip获取不对。帮忙看看。

![1508402174442](https://user-images.githubusercontent.com/15799158/31761781-bd60b714-b4eb-11e7-9739-2f57ebec7d33.jpg)

**Comment by chenhw2** [comment]
这类二级宽带没有公网IP的吧？

**Comment by qianjun2659** [comment]
有的。花生壳，群晖自带ddns都可以获取到。

**Comment by chenhw2** [comment]
现在可以增加环境变量```IPAPI```来指定获取IP的URL了
