### ISSUE TITLE
威联通 TS-228不能用

### ISSUE THREAD

**Issue by jasonlee46** [chenhw2/aliyun-ddns-cli#9]
container里可以搜索到，但是无法安装，显示不能与ARM NAS兼容。

**Comment by chenhw2** [comment]
这个Docker只支援x86_64, 手上也没有ARM的Docker可以试验

**Comment by jasonlee46** [comment]
大神，不打算写一个吗？现在ARM架构的越来越多。可以donate的。

**Comment by chenhw2** [comment]
mail to honwen.chan#gmail.com

**Comment by jasonlee46** [comment]
试了一天，除了admin账户之外的其他用户账户都无法使用container，没法发给你试用了。

**Comment by chenhw2** [comment]
那没办法了

**Comment by chenhw2** [comment]
https://github.com/chenhw2/aliyun-ddns-cli/releases

有ARM的bin可以直接跑，你可以想办法直接跑在NAS上

**Comment by jasonlee46** [comment]
还是不行，我试着导入镜像，文件错误。
![image](https://user-images.githubusercontent.com/33628699/33194261-acc65b22-d109-11e7-8f93-046cdac1e9e9.png)

**Comment by chenhw2** [comment]
从来没出过ARM的docekr 镜像，这是要SSH到NAS上面跑的，没有Linux基础的话困难

**Comment by jasonlee46** [comment]
Putty没问题，我试试。
